apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ConfigMap.name2 }}
  namespace: {{ .Values.namespace.name }}
data:
  postgresql.conf: |-
    # DB Version: 12
    # OS Type: linux
    # DB Type: oltp
    # Total Memory (RAM): 16 GB
    # CPUs num: 4
    # Connections num: 9999
    # Data Storage: ssd
    # https://pgtune.leopard.in.ua/#/
    # 2020-10-29
    listen_addresses = '*'
    max_connections = 9999
    shared_buffers = 4GB
    effective_cache_size = 12GB
    maintenance_work_mem = 1GB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 209kB
    min_wal_size = 2GB
    max_wal_size = 8GB
    max_worker_processes = 4
    max_parallel_workers_per_gather = 2
    max_parallel_workers = 4
    max_parallel_maintenance_workers = 2