apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: apim-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apim-secret
                  key: password
          restart: always
          ports:
            - containerPort: {{ .Values.container.port1 }}
          volumeMounts:
            - name: {{ .Values.ConfigMap.name1 }}
              mountPath: /docker-entrypoint-initdb.d
            # - name: azure-volume
            #   mountPath: /mnt/azure
            #   readOnly: false
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      volumes:
        - name: {{ .Values.ConfigMap.name1 }}
          configMap:
            name: {{ .Values.ConfigMap.name1 }}
        # - name: azure-volume
        #   persistentVolumeClaim:
        #     claimName: azure-persistent-volume-claim