apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: apim-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apim-secret
                  key: password
          restart: always
          ports:
            - containerPort: {{ .Values.container.port1 }}
          volumeMounts:
            - name: {{ .Values.ConfigMap.name }}
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: {{ .Values.ConfigMap.name }}
          configMap:
            name: {{ .Values.ConfigMap.name }}
