apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azure-persistent-volume-claim
    namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi