apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.container.port1 }}
      targetPort: {{ .Values.container.port1 }}