apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          env:
            - name: EXTERNAL_IP
              value: {{ .Values.app.externalip }}
          ports:
            - containerPort: {{ .Values.container.port1 }}
            - containerPort: {{ .Values.container.port2 }}
            - containerPort: {{ .Values.container.port3 }}
            - containerPort: {{ .Values.container.port4 }}
          volumeMounts:
            - name: apim-deployent-toml
              mountPath: /home/apim-postgres/repository/conf/deployment.toml
              subPath: deployment.toml
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      volumes:
        - name: apim-deployent-toml
          configMap:
            name: apim-deployent-toml