apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apim-ingress
spec:
  defaultBackend:
    service:
      name: {{ .Values.service.name }}
      port:
        number: {{ .Values.container.port1 }}
