apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.container.port1 }}
      targetPort: {{ .Values.container.port1 }}
    - name: http-tls
      protocol: TCP
      port: {{ .Values.container.port2 }}
      targetPort: {{ .Values.container.port2 }}
    - name: http
      protocol: TCP
      port: {{ .Values.container.port3 }}
      targetPort: {{ .Values.container.port3 }}